#!/bin/bash

set -e
set -x

git submodule update --init
nosetests $@ --logging-filter=timestream --with-coverage --cover-package timestream
test -n "$(which flake8)" && flake8 --exit-zero --max-line-length=85 timestream tests --exclude tests/helpers.py
